In [3]:
import pandas as pd
import csv
import sys

In [4]:
df = pd.read_csv("baseball.csv", index_col=0)

In [5]:
df.head()

,actual,prediction,IDfg,Season,Name,Team,Age,G,AB,PA,...,Events,CStr%,CSW%,Next_WAR,team_code,player_season,war_corr,war_diff,war_season,diff
5006,1.2,1.426571,1,2007,Alfredo Amezaga,FLA,0.384615,0.743590,0.431655,0.429066,...,0.0,0.527660,0.396476,1.2,0.352941,1,1.000000,1.200000,0.998355,0.226571
1925,1.4,0.610158,2,2007,Garret Anderson,LAA,0.615385,0.529915,0.462230,0.432526,...,0.0,0.442553,0.480176,1.4,0.441176,5,-0.692192,1.371429,0.887427,0.789842
3102,-0.1,0.507188,10,2007,David Eckstein,STL,0.500000,0.606838,0.492806,0.491349,...,0.0,0.676596,0.436123,-0.1,0.852941,5,-0.694330,0.836735,0.758010,0.607188
5797,0.6,0.957194,11,2007,Darin Erstad,CHW,0.538462,0.350427,0.269784,0.254325,...,0.0,0.765957,0.691630,0.6,0.205882,4,-0.828562,0.803922,0.758010,0.357194
1109,4.8,2.145165,15,2007,Troy Glaus,TOR,0.423077,0.589744,0.404676,0.442907,...,0.0,0.634043,0.704846,4.8,0.970588,5,0.231396,0.897059,1.127772,2.654835

In [9]:
player = input("Enter your favourite player: ")
player
df1 = df[df['Name'] == player]
df1

Enter your favourite player:  Troy Glaus

,actual,prediction,IDfg,Season,Name,Team,Age,G,AB,PA,...,Events,CStr%,CSW%,Next_WAR,team_code,player_season,war_corr,war_diff,war_season,diff
1109,4.8,2.145165,15,2007,Troy Glaus,TOR,0.423077,0.589744,0.404676,0.442907,...,0.0,0.634043,0.704846,4.8,0.970588,5,0.231396,0.897059,1.127772,2.654835
815,-0.1,3.093860,15,2008,Troy Glaus,STL,0.461538,0.897436,0.690647,0.756055,...,0.0,0.565957,0.581498,-0.1,0.852941,6,0.516997,1.344262,1.533970,3.193860